FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Multiplayer RPG

Multiplayer RPG is an API for a new exciting multiplayer RPG.

## Character services [/character/{playerID}]

### Unlock character [POST]

+ Request (application/json)

        {
            "type": "warrior",
            "element": "fire"
        }
        
+ Response 200 (application/json)

        {
            "type": "warrior",
            "level":1,
            "life": 500,
            "attack": 25,
            "defense": 20,
            "magicAttack": 5,
            "magicDefense": 5,
            "element": "fire"
        }

## Character stats services [/stats/{playerID}/{character}]

### Add stats points [POST]

+ Request (application/json)

        {
            "statToIncrease": "attack",
            "pointsToAdd": 5
        }
        
+ Response 200

## Team services [/team/{playerID}]

### Get team [GET]

+ Response 200 (application/json)

        [
            {
                "type": "warrior",
                "level":1,
                "life": 500,
                "attack": 30,
                "defense": 20,
                "magicAttack": 5,
                "magicDefense": 5,
                "element": "fire"
            },
            
            {
                "type": "archer",
                "level":1,
                "life": 300,
                "attack": 15,
                "defense": 15,
                "magicAttack": 10,
                "magicDefense": 10,
                "element": "grass"
            },
            
            {
                "type": "necromancer",
                "level":1,
                "life": 250,
                "attack": 10,
                "defense": 15,
                "magicAttack": 30,
                "magicDefense": 20,
                "element": "water"
            }
        ]

### Change team [POST]

+ Request (application/json)

        [
            {
                "type": "archer",
                "level":1,
                "element": "water"
            },
            
            {
                "type": "archer",
                "level":1,
                "element": "fire"
            },
            
            {
                "type": "necromancer",
                "level":1,
                "element": "grass"
            }
        ]

+ Response 200

## Battle services [/battle/{battleID}{?winnerID,losserID}]

### Report battle [POST]

+ Request (application/json)

        {
            "pointsForWinner": 100,
            "pointsForLosser": 50
        }

+ Response 200